version: '3.8'
services:

  mysql:
    image: mysql
    container_name: mysql-movieflix
    environment:
      MYSQL_PASSWORD_ROOT: root
      MYSQL_DATABASE: movieflix
    ports:
    - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  -mysql_volume: