micronaut:
  application:
    name: movieFlix

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

#datasources:
#  default:
#    url: jdbc:mysql://localhost:3306/movieflix?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: ${BD_USER:root}
#    password: ${BD_PASSWORD:root}
#    schema-generate: CREATE_DROP
#    dialect: MYSQL
#
#jpa:
#  default:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        hbm2ddl:
#          auto: update
